### ISSUE TITLE
Bug report on vm

### ISSUE THREAD

**Issue by Proskke** [p1r-a-t3/Hacker-Playbook-Utility#1]
Hi, Great script but i found some bugs
![image](https://user-images.githubusercontent.com/15311168/39677785-3cb890d6-5181-11e8-9a20-09f2675c4902.png)
![image](https://user-images.githubusercontent.com/15311168/39677788-50f9da00-5181-11e8-866b-198d2d3f1c3c.png)
![image](https://user-images.githubusercontent.com/15311168/39677792-5bd67794-5181-11e8-9aa7-9dcc80858e6f.png)
![image](https://user-images.githubusercontent.com/15311168/39677794-69823b80-5181-11e8-9ed6-a01c395ec22b.png)

**Comment by shepherd-06** [comment]
@Proskke, I have just pushed a new update. Please try it. I have addressed all the issues in there. 
Thanks :+1:
